/*Assessment Lab 2*/


#include <stdio.h>
#include <stdlib.h>
#include <limits.h>
#include <math.h>

void pixelMean(float *r, float *g, float *b);


int main() {
 //Task 3:  Modify your program so that the image data is read from a file instead of generated by the rand()
 //function. The data is numbers that srand() generates but from a file intead of srand()
 
/*srand(0);

    for(y = 0; y < 5; y++) {
        for(x = 0; x < 5; x++) {
            image[x][y][0] = (float)rand()/(float)INT_MAX;
            image[x][y][1] = (float)rand()/(float)INT_MAX;
            image[x][y][2] = (float)rand()/(float)INT_MAX;
 */
   
    
  FILE *input;    //Assign the file data a pointer
  input = fopen("ArrayInput", "r");   //  opens the file for reading
   
float image[5][5][3];   // Declares an array to hold the data
int x, y;           // 3d array so and x and y values needed to be printed so x and y are declared as int datadypes
   if(input == NULL) {
       printf("Error Reading File\n");
       exit (0);
       
   }
   
   //Take the sum of each array first
   
    float rt = 0, gt = 0, bt = 0;  //intially before any data is read, these values are et to zero
    
    
    float rm, gm, bm;           //These float datatypes are for storing the mean value once calculated
    
    //nested for loop to test each element of the 3D array by reading from file first
        for(y = 0; y < 2; y++){
            for(x = 0; x < 5; x++){
                fscanf(input,"%f", &image[x][y][0]);
                fscanf(input,"%f", &image[x][y][1]);
                fscanf(input,"%f", &image[x][y][2]);
                
                //Takes the data read form the file and computes the total
        
                    rt = image[x][y][0];
                    gt = image[x][y][1];
                    bt = image[x][y][2];
                //Takes the total and divides it by the number of arrays
        
                        rm = (rt + gt + bt)/3.0;
                        gm = (rt + gt + bt)/3.0;
                        bm = (rt + gt + bt)/3.0;
                //Prints the valuje of the x and y coordintate in the array, then prints the r, g, and b average for each
                //These values should be the same as the image data is now in gray scale.(a value between 0 and 1).
                             printf("%d %d: %f %f %f\n", x, y, rm, gm, bm);
        }
    }
    
            fclose(input);

    return 0;
}



void pixelMean(float *r, float *g, float *b){
    *r = (*r + *g + *b)/3.0;
    *g = (*r + *g + *b)/3.0;
    *b = (*r + *g + *b)/3.0;
        
}
    
//Task 1: Within the main() function, write code which converts each pixel’s colour to a greyscale value
//equal to the mean of the red, green, and blue values (ie: (r+g+b)/3.0)).

/* float rt = 0, gt = 0, bt = 0;
    float rm, gm, bm;
    
    
for(y = 0; y < 2; y++){
    for(x = 0; x < 5; x++){
        rt = image[x][y][0];
        gt = image[x][y][1];
        bt = image[x][y][2];
        
rm = (rt + gt + bt)/3.0;
gm = (rt + gt + bt)/3.0;
bm = (rt + gt + bt)/3.0;

printf("%d %d: %f %f %f\n", x, y, rm, gm, bm);
    }
}

printf("%d %d: %f %f %f\n", x, y, rm, gm, bm);*/

//Task 2: Modify your program so that the mean calculation, and pixel data modification, is performed in a
//function. The function should accept pointers to three floats and modify the three array values
//directly.
/*float r, g, b;
for(y = 0; y < 5; y++){
    for(x = 0; x < 5; x++){
        r = image[x][y][0];
        g = image[x][y][1];
        b = image[x][y][2];
        
    pixelMean(&r, &g, &b);
    printf("%d %d: %f %f %f\n", x, y, r, g, b);
        }
    }
    printf("%d %d: %f %f %f\n", x, y, r, g, b);

return 0;
}



void pixelMean(float *r, float *g, float *b){
    *r = (*r + *g + *b)/3.0;
    *g = (*r + *g + *b)/3.0;
    *b = (*r + *g + *b)/3.0;
        
}*/
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    